/**
 */
package net.descartesresearch.librede.configuration.provider;

import java.util.ArrayList;
import java.util.Collection;

import net.descartesresearch.librede.configuration.util.ConfigurationAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ConfigurationItemProviderAdapterFactory extends ConfigurationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ConfigurationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.LibredeConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LibredeConfigurationItemProvider libredeConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.LibredeConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLibredeConfigurationAdapter() {
		if (libredeConfigurationItemProvider == null) {
			libredeConfigurationItemProvider = new LibredeConfigurationItemProvider(this);
		}

		return libredeConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.DataProviderConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataProviderConfigurationItemProvider dataProviderConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.DataProviderConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataProviderConfigurationAdapter() {
		if (dataProviderConfigurationItemProvider == null) {
			dataProviderConfigurationItemProvider = new DataProviderConfigurationItemProvider(this);
		}

		return dataProviderConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.DataSourceConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataSourceConfigurationItemProvider dataSourceConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.DataSourceConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataSourceConfigurationAdapter() {
		if (dataSourceConfigurationItemProvider == null) {
			dataSourceConfigurationItemProvider = new DataSourceConfigurationItemProvider(this);
		}

		return dataSourceConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.WorkloadDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkloadDescriptionItemProvider workloadDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.WorkloadDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkloadDescriptionAdapter() {
		if (workloadDescriptionItemProvider == null) {
			workloadDescriptionItemProvider = new WorkloadDescriptionItemProvider(this);
		}

		return workloadDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.InputSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputSpecificationItemProvider inputSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.InputSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputSpecificationAdapter() {
		if (inputSpecificationItemProvider == null) {
			inputSpecificationItemProvider = new InputSpecificationItemProvider(this);
		}

		return inputSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.EstimationApproachConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstimationApproachConfigurationItemProvider estimationApproachConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.EstimationApproachConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEstimationApproachConfigurationAdapter() {
		if (estimationApproachConfigurationItemProvider == null) {
			estimationApproachConfigurationItemProvider = new EstimationApproachConfigurationItemProvider(this);
		}

		return estimationApproachConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.OutputSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputSpecificationItemProvider outputSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.OutputSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputSpecificationAdapter() {
		if (outputSpecificationItemProvider == null) {
			outputSpecificationItemProvider = new OutputSpecificationItemProvider(this);
		}

		return outputSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.Resource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourceItemProvider resourceItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.Resource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourceAdapter() {
		if (resourceItemProvider == null) {
			resourceItemProvider = new ResourceItemProvider(this);
		}

		return resourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.TraceConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TraceConfigurationItemProvider traceConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.TraceConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTraceConfigurationAdapter() {
		if (traceConfigurationItemProvider == null) {
			traceConfigurationItemProvider = new TraceConfigurationItemProvider(this);
		}

		return traceConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.EstimationSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstimationSpecificationItemProvider estimationSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.EstimationSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEstimationSpecificationAdapter() {
		if (estimationSpecificationItemProvider == null) {
			estimationSpecificationItemProvider = new EstimationSpecificationItemProvider(this);
		}

		return estimationSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.ValidationSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValidationSpecificationItemProvider validationSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.ValidationSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValidationSpecificationAdapter() {
		if (validationSpecificationItemProvider == null) {
			validationSpecificationItemProvider = new ValidationSpecificationItemProvider(this);
		}

		return validationSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.ValidatorConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValidatorConfigurationItemProvider validatorConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.ValidatorConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValidatorConfigurationAdapter() {
		if (validatorConfigurationItemProvider == null) {
			validatorConfigurationItemProvider = new ValidatorConfigurationItemProvider(this);
		}

		return validatorConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.descartesresearch.librede.configuration.ExporterConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExporterConfigurationItemProvider exporterConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link net.descartesresearch.librede.configuration.ExporterConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExporterConfigurationAdapter() {
		if (exporterConfigurationItemProvider == null) {
			exporterConfigurationItemProvider = new ExporterConfigurationItemProvider(this);
		}

		return exporterConfigurationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (libredeConfigurationItemProvider != null) libredeConfigurationItemProvider.dispose();
		if (dataProviderConfigurationItemProvider != null) dataProviderConfigurationItemProvider.dispose();
		if (workloadDescriptionItemProvider != null) workloadDescriptionItemProvider.dispose();
		if (inputSpecificationItemProvider != null) inputSpecificationItemProvider.dispose();
		if (estimationApproachConfigurationItemProvider != null) estimationApproachConfigurationItemProvider.dispose();
		if (outputSpecificationItemProvider != null) outputSpecificationItemProvider.dispose();
		if (resourceItemProvider != null) resourceItemProvider.dispose();
		if (serviceItemProvider != null) serviceItemProvider.dispose();
		if (traceConfigurationItemProvider != null) traceConfigurationItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (estimationSpecificationItemProvider != null) estimationSpecificationItemProvider.dispose();
		if (validationSpecificationItemProvider != null) validationSpecificationItemProvider.dispose();
		if (dataSourceConfigurationItemProvider != null) dataSourceConfigurationItemProvider.dispose();
		if (validatorConfigurationItemProvider != null) validatorConfigurationItemProvider.dispose();
		if (exporterConfigurationItemProvider != null) exporterConfigurationItemProvider.dispose();
	}

}
