<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configuration" nsURI="http://www.descartes-research.net/librede/configuration/1.0"
    nsPrefix="librede">
  <eClassifiers xsi:type="ecore:EClass" name="LibredeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workloadDescription" lowerBound="1"
        eType="#//WorkloadDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//InputSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estimation" lowerBound="1"
        eType="#//EstimationSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//OutputSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" lowerBound="1"
        eType="#//ValidationSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceConfiguration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkloadDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSources" lowerBound="1"
        upperBound="-1" eType="#//DataSourceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observations" upperBound="-1"
        eType="#//TraceConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EstimationApproachConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exporters" upperBound="-1"
        eType="#//ExporterConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//ModelEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfServers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedulingStrategy" eType="#//SchedulingStrategy"
        defaultValueLiteral="Unkown"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childResources" upperBound="-1"
        eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demands" upperBound="-1"
        eType="#//ResourceDemand" eOpposite="#//ResourceDemand/resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessingServices" upperBound="-1"
        eType="#//Service" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//ModelEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundService" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedResources" upperBound="-1"
        eType="#//Resource" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callees" upperBound="-1"
        eType="#//ExternalCall" eOpposite="#//ExternalCall/calledService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchedulingStrategy">
    <eLiterals name="FCFS"/>
    <eLiterals name="PS"/>
    <eLiterals name="IS"/>
    <eLiterals name="UNKOWN" literal="Unkown"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1">
      <eGenericType eClassifier="ecore:EClass metrics.ecore#//Metric">
        <eTypeArguments>
          <eUpperBound eClassifier="ecore:EClass units.ecore#//Dimension"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" lowerBound="1"
        eType="#//DataSourceConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" lowerBound="1"
        upperBound="-1" eType="#//TraceToEntityMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1">
      <eGenericType eClassifier="ecore:EClass units.ecore#//Unit">
        <eTypeArguments>
          <eUpperBound eClassifier="ecore:EClass units.ecore#//Dimension"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interval" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass units.ecore#//Quantity">
        <eTypeArguments eClassifier="ecore:EClass units.ecore#//Time"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="ecore:EEnum metrics.ecore#//Aggregation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EstimationSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="approaches" upperBound="-1"
        eType="#//EstimationApproachConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recursive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="window" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithms" upperBound="-1"
        eType="#//EstimationAlgorithmConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepSize" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass units.ecore#//Quantity">
        <eTypeArguments eClassifier="ecore:EClass units.ecore#//Time"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTimestamp" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass units.ecore#//Quantity">
        <eTypeArguments eClassifier="ecore:EClass units.ecore#//Time"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endTimestamp" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass units.ecore#//Quantity">
        <eTypeArguments eClassifier="ecore:EClass units.ecore#//Time"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validators" upperBound="-1"
        eType="#//ValidatorConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationFolds" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validateEstimates" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExporterConfiguration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileTraceConfiguration" eSuperTypes="#//TraceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceToEntityMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//ModelEntity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//TraceFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelEntity" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EstimationAlgorithmConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceFilter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceDemand" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
        eType="#//Resource" eOpposite="#//Resource/demands"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalCall" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledService" lowerBound="1"
        eType="#//Service" eOpposite="#//Service/callees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subServices" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" eSuperTypes="#//ModelEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//Service" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
