<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metrics" nsURI="http://www.descartes-research.net/librede/metrics/1.0"
    nsPrefix="librede-metrics">
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="ecore:EClass units.ecore#//Dimension" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowedAggregations" lowerBound="1"
        upperBound="-1" eType="#//Aggregation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Aggregation">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="AVERAGE" value="1" literal="AVERAGE"/>
    <eLiterals name="MAXIMUM" value="2"/>
    <eLiterals name="MINIMUM" value="3" literal=""/>
    <eLiterals name="SUM" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetricsRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metric" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
